// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetRequest struct {
	ShortLink            string   `protobuf:"bytes,1,opt,name=ShortLink,proto3" json:"ShortLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetShortLink() string {
	if m != nil {
		return m.ShortLink
	}
	return ""
}

type GetRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	LongLink             string   `protobuf:"bytes,3,opt,name=LongLink,proto3" json:"LongLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRespond) Reset()         { *m = GetRespond{} }
func (m *GetRespond) String() string { return proto.CompactTextString(m) }
func (*GetRespond) ProtoMessage()    {}
func (*GetRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *GetRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRespond.Unmarshal(m, b)
}
func (m *GetRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRespond.Marshal(b, m, deterministic)
}
func (m *GetRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRespond.Merge(m, src)
}
func (m *GetRespond) XXX_Size() int {
	return xxx_messageInfo_GetRespond.Size(m)
}
func (m *GetRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRespond.DiscardUnknown(m)
}

var xxx_messageInfo_GetRespond proto.InternalMessageInfo

func (m *GetRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetRespond) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetRespond) GetLongLink() string {
	if m != nil {
		return m.LongLink
	}
	return ""
}

type ChangeRequest struct {
	LongLink             string   `protobuf:"bytes,1,opt,name=LongLink,proto3" json:"LongLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRequest) Reset()         { *m = ChangeRequest{} }
func (m *ChangeRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeRequest) ProtoMessage()    {}
func (*ChangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *ChangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRequest.Unmarshal(m, b)
}
func (m *ChangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRequest.Marshal(b, m, deterministic)
}
func (m *ChangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRequest.Merge(m, src)
}
func (m *ChangeRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeRequest.Size(m)
}
func (m *ChangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRequest proto.InternalMessageInfo

func (m *ChangeRequest) GetLongLink() string {
	if m != nil {
		return m.LongLink
	}
	return ""
}

type ChangeRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeRespond) Reset()         { *m = ChangeRespond{} }
func (m *ChangeRespond) String() string { return proto.CompactTextString(m) }
func (*ChangeRespond) ProtoMessage()    {}
func (*ChangeRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *ChangeRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeRespond.Unmarshal(m, b)
}
func (m *ChangeRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeRespond.Marshal(b, m, deterministic)
}
func (m *ChangeRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeRespond.Merge(m, src)
}
func (m *ChangeRespond) XXX_Size() int {
	return xxx_messageInfo_ChangeRespond.Size(m)
}
func (m *ChangeRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeRespond.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeRespond proto.InternalMessageInfo

func (m *ChangeRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ChangeRespond) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "proto.GetRequest")
	proto.RegisterType((*GetRespond)(nil), "proto.GetRespond")
	proto.RegisterType((*ChangeRequest)(nil), "proto.ChangeRequest")
	proto.RegisterType((*ChangeRespond)(nil), "proto.ChangeRespond")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x5a, 0x5c, 0x5c, 0xee, 0xa9, 0x25,
	0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x32, 0x5c, 0x9c, 0xc1, 0x19, 0xf9, 0x45, 0x25,
	0x3e, 0x99, 0x79, 0xd9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x08, 0x01, 0x25, 0x3f, 0xa8,
	0xda, 0xe2, 0x82, 0xfc, 0xbc, 0x14, 0x21, 0x21, 0x2e, 0x16, 0xe7, 0xfc, 0x94, 0x54, 0xb0, 0x32,
	0xd6, 0x20, 0x30, 0x5b, 0x48, 0x80, 0x8b, 0xd9, 0xb7, 0x38, 0x5d, 0x82, 0x09, 0xac, 0x13, 0xc4,
	0x14, 0x92, 0xe2, 0xe2, 0xf0, 0xc9, 0xcf, 0x4b, 0x07, 0x1b, 0xc8, 0x0c, 0x16, 0x86, 0xf3, 0x95,
	0xb4, 0xb9, 0x78, 0x9d, 0x33, 0x12, 0xf3, 0xd2, 0x53, 0x61, 0xd6, 0x23, 0x2b, 0x66, 0x44, 0x53,
	0x6c, 0x8a, 0x50, 0x4c, 0x82, 0xfd, 0x46, 0x05, 0x5c, 0xec, 0xee, 0x89, 0x25, 0xa9, 0xe5, 0x89,
	0x95, 0x42, 0xba, 0x5c, 0xcc, 0xee, 0xa9, 0x25, 0x42, 0x82, 0x90, 0x00, 0xd0, 0x43, 0x78, 0x5b,
	0x0a, 0x45, 0x08, 0x6c, 0xba, 0x12, 0x83, 0x90, 0x19, 0x17, 0x1b, 0xc4, 0x42, 0x21, 0x11, 0xa8,
	0x34, 0x8a, 0x63, 0xa5, 0xd0, 0x45, 0xa1, 0xfa, 0x92, 0xd8, 0xc0, 0xc2, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x08, 0xba, 0x1a, 0xcf, 0x6c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GatewayClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetRespond, error)
	Change(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (*ChangeRespond, error)
}

type gatewayClient struct {
	cc *grpc.ClientConn
}

func NewGatewayClient(cc *grpc.ClientConn) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetRespond, error) {
	out := new(GetRespond)
	err := c.cc.Invoke(ctx, "/proto.Gateway/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Change(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (*ChangeRespond, error) {
	out := new(ChangeRespond)
	err := c.cc.Invoke(ctx, "/proto.Gateway/Change", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
type GatewayServer interface {
	Get(context.Context, *GetRequest) (*GetRespond, error)
	Change(context.Context, *ChangeRequest) (*ChangeRespond, error)
}

// UnimplementedGatewayServer can be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (*UnimplementedGatewayServer) Get(ctx context.Context, req *GetRequest) (*GetRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedGatewayServer) Change(ctx context.Context, req *ChangeRequest) (*ChangeRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Change not implemented")
}

func RegisterGatewayServer(s *grpc.Server, srv GatewayServer) {
	s.RegisterService(&_Gateway_serviceDesc, srv)
}

func _Gateway_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gateway/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Change_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Change(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Gateway/Change",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Change(ctx, req.(*ChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gateway_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Gateway_Get_Handler,
		},
		{
			MethodName: "Change",
			Handler:    _Gateway_Change_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
