// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InfoRequest struct {
	ShortLink            string   `protobuf:"bytes,1,opt,name=ShortLink,proto3" json:"ShortLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (m *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(m, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

func (m *InfoRequest) GetShortLink() string {
	if m != nil {
		return m.ShortLink
	}
	return ""
}

type ShortLinkInfo struct {
	ShortId              int64    `protobuf:"varint,1,opt,name=ShortId,proto3" json:"ShortId,omitempty"`
	ShortCode            string   `protobuf:"bytes,2,opt,name=ShortCode,proto3" json:"ShortCode,omitempty"`
	LongLink             string   `protobuf:"bytes,3,opt,name=LongLink,proto3" json:"LongLink,omitempty"`
	CreatedAt            string   `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortLinkInfo) Reset()         { *m = ShortLinkInfo{} }
func (m *ShortLinkInfo) String() string { return proto.CompactTextString(m) }
func (*ShortLinkInfo) ProtoMessage()    {}
func (*ShortLinkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ShortLinkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortLinkInfo.Unmarshal(m, b)
}
func (m *ShortLinkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortLinkInfo.Marshal(b, m, deterministic)
}
func (m *ShortLinkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortLinkInfo.Merge(m, src)
}
func (m *ShortLinkInfo) XXX_Size() int {
	return xxx_messageInfo_ShortLinkInfo.Size(m)
}
func (m *ShortLinkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortLinkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ShortLinkInfo proto.InternalMessageInfo

func (m *ShortLinkInfo) GetShortId() int64 {
	if m != nil {
		return m.ShortId
	}
	return 0
}

func (m *ShortLinkInfo) GetShortCode() string {
	if m != nil {
		return m.ShortCode
	}
	return ""
}

func (m *ShortLinkInfo) GetLongLink() string {
	if m != nil {
		return m.LongLink
	}
	return ""
}

func (m *ShortLinkInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ShortLinkInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type InfoRespond struct {
	Code                 int32          `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string         `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	ShortLink            *ShortLinkInfo `protobuf:"bytes,3,opt,name=ShortLink,proto3" json:"ShortLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InfoRespond) Reset()         { *m = InfoRespond{} }
func (m *InfoRespond) String() string { return proto.CompactTextString(m) }
func (*InfoRespond) ProtoMessage()    {}
func (*InfoRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *InfoRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRespond.Unmarshal(m, b)
}
func (m *InfoRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRespond.Marshal(b, m, deterministic)
}
func (m *InfoRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRespond.Merge(m, src)
}
func (m *InfoRespond) XXX_Size() int {
	return xxx_messageInfo_InfoRespond.Size(m)
}
func (m *InfoRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRespond.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRespond proto.InternalMessageInfo

func (m *InfoRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *InfoRespond) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *InfoRespond) GetShortLink() *ShortLinkInfo {
	if m != nil {
		return m.ShortLink
	}
	return nil
}

type ShortenRequest struct {
	LongLink             string   `protobuf:"bytes,1,opt,name=LongLink,proto3" json:"LongLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenRequest) Reset()         { *m = ShortenRequest{} }
func (m *ShortenRequest) String() string { return proto.CompactTextString(m) }
func (*ShortenRequest) ProtoMessage()    {}
func (*ShortenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *ShortenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenRequest.Unmarshal(m, b)
}
func (m *ShortenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenRequest.Marshal(b, m, deterministic)
}
func (m *ShortenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenRequest.Merge(m, src)
}
func (m *ShortenRequest) XXX_Size() int {
	return xxx_messageInfo_ShortenRequest.Size(m)
}
func (m *ShortenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenRequest proto.InternalMessageInfo

func (m *ShortenRequest) GetLongLink() string {
	if m != nil {
		return m.LongLink
	}
	return ""
}

type ShortenRespond struct {
	Code                 int32    `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	LongLink             string   `protobuf:"bytes,3,opt,name=LongLink,proto3" json:"LongLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortenRespond) Reset()         { *m = ShortenRespond{} }
func (m *ShortenRespond) String() string { return proto.CompactTextString(m) }
func (*ShortenRespond) ProtoMessage()    {}
func (*ShortenRespond) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *ShortenRespond) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortenRespond.Unmarshal(m, b)
}
func (m *ShortenRespond) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortenRespond.Marshal(b, m, deterministic)
}
func (m *ShortenRespond) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortenRespond.Merge(m, src)
}
func (m *ShortenRespond) XXX_Size() int {
	return xxx_messageInfo_ShortenRespond.Size(m)
}
func (m *ShortenRespond) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortenRespond.DiscardUnknown(m)
}

var xxx_messageInfo_ShortenRespond proto.InternalMessageInfo

func (m *ShortenRespond) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ShortenRespond) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ShortenRespond) GetLongLink() string {
	if m != nil {
		return m.LongLink
	}
	return ""
}

func init() {
	proto.RegisterType((*InfoRequest)(nil), "proto.InfoRequest")
	proto.RegisterType((*ShortLinkInfo)(nil), "proto.ShortLinkInfo")
	proto.RegisterType((*InfoRespond)(nil), "proto.InfoRespond")
	proto.RegisterType((*ShortenRequest)(nil), "proto.ShortenRequest")
	proto.RegisterType((*ShortenRespond)(nil), "proto.ShortenRespond")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xad, 0x6d, 0xd5, 0xce, 0xa2, 0xc8, 0xa0, 0x50, 0x8a, 0x07, 0xc9, 0x49, 0x50, 0x16,
	0xa9, 0x27, 0x8f, 0xb2, 0xa7, 0x85, 0xf5, 0x12, 0xf1, 0x01, 0x56, 0x12, 0x6b, 0x11, 0x92, 0xda,
	0x46, 0xf0, 0x6d, 0x7c, 0x55, 0xc9, 0x34, 0x8d, 0x53, 0x04, 0x61, 0x4f, 0xc9, 0x7c, 0x93, 0xc9,
	0xfc, 0xff, 0x0c, 0x14, 0xdb, 0xae, 0x5d, 0x76, 0xbd, 0x75, 0x16, 0x73, 0x3a, 0xc4, 0x35, 0x2c,
	0xd6, 0xe6, 0xd5, 0x4a, 0xfd, 0xf1, 0xa9, 0x07, 0x87, 0x17, 0x50, 0x3c, 0xbd, 0xd9, 0xde, 0x6d,
	0x5a, 0xf3, 0x5e, 0x26, 0x97, 0xc9, 0x55, 0x21, 0x7f, 0x81, 0xf8, 0x4e, 0xe0, 0x38, 0x46, 0xbe,
	0x0c, 0x4b, 0x38, 0x24, 0xb0, 0x56, 0xf4, 0x3a, 0x95, 0x53, 0x18, 0x7f, 0x5a, 0x59, 0xa5, 0xcb,
	0x7d, 0xf6, 0x93, 0x07, 0x58, 0xc1, 0xd1, 0xc6, 0x9a, 0x86, 0xda, 0xa4, 0x94, 0x8c, 0xb1, 0xaf,
	0x5c, 0xf5, 0x7a, 0xeb, 0xb4, 0x7a, 0x70, 0x65, 0x36, 0x56, 0x46, 0xe0, 0xb3, 0xcf, 0x9d, 0x0a,
	0xd9, 0x7c, 0xcc, 0x46, 0x20, 0x9a, 0xc9, 0xce, 0xd0, 0x59, 0xa3, 0x10, 0x21, 0xa3, 0xfe, 0x5e,
	0x5b, 0x2e, 0xe9, 0x8e, 0xa7, 0x90, 0x3e, 0x0e, 0x4d, 0x90, 0xe4, 0xaf, 0x58, 0x73, 0xd3, 0x5e,
	0xcd, 0xa2, 0x3e, 0x1b, 0xa7, 0xb4, 0x9c, 0xb9, 0xe5, 0xa3, 0xb8, 0x81, 0x13, 0x0a, 0xb4, 0x99,
	0x46, 0xc7, 0x2d, 0x25, 0x73, 0x4b, 0x42, 0xb2, 0xd7, 0xbb, 0x28, 0xfb, 0x67, 0x4c, 0xf5, 0x17,
	0x53, 0x8d, 0xb7, 0x90, 0xd1, 0x3e, 0x30, 0xe8, 0x66, 0x3b, 0xad, 0xe6, 0x8c, 0xda, 0x8b, 0x3d,
	0xbc, 0x0f, 0x9b, 0xd3, 0x06, 0xcf, 0xb9, 0xd9, 0x68, 0xa8, 0xfa, 0x83, 0x43, 0xe9, 0xcb, 0x01,
	0xf1, 0xbb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x71, 0x61, 0x0f, 0x4e, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ShortLinkClient is the client API for ShortLink service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ShortLinkClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoRespond, error)
	Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenRespond, error)
}

type shortLinkClient struct {
	cc *grpc.ClientConn
}

func NewShortLinkClient(cc *grpc.ClientConn) ShortLinkClient {
	return &shortLinkClient{cc}
}

func (c *shortLinkClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoRespond, error) {
	out := new(InfoRespond)
	err := c.cc.Invoke(ctx, "/proto.ShortLink/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shortLinkClient) Shorten(ctx context.Context, in *ShortenRequest, opts ...grpc.CallOption) (*ShortenRespond, error) {
	out := new(ShortenRespond)
	err := c.cc.Invoke(ctx, "/proto.ShortLink/Shorten", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShortLinkServer is the server API for ShortLink service.
type ShortLinkServer interface {
	Info(context.Context, *InfoRequest) (*InfoRespond, error)
	Shorten(context.Context, *ShortenRequest) (*ShortenRespond, error)
}

// UnimplementedShortLinkServer can be embedded to have forward compatible implementations.
type UnimplementedShortLinkServer struct {
}

func (*UnimplementedShortLinkServer) Info(ctx context.Context, req *InfoRequest) (*InfoRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}
func (*UnimplementedShortLinkServer) Shorten(ctx context.Context, req *ShortenRequest) (*ShortenRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shorten not implemented")
}

func RegisterShortLinkServer(s *grpc.Server, srv ShortLinkServer) {
	s.RegisterService(&_ShortLink_serviceDesc, srv)
}

func _ShortLink_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortLinkServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShortLink/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortLinkServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShortLink_Shorten_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShortenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShortLinkServer).Shorten(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ShortLink/Shorten",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShortLinkServer).Shorten(ctx, req.(*ShortenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShortLink_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShortLink",
	HandlerType: (*ShortLinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _ShortLink_Info_Handler,
		},
		{
			MethodName: "Shorten",
			Handler:    _ShortLink_Shorten_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
