language:
  - go

sudo: true

go:
  - "1.13.x"

env:
  - GO111MODULE=on

before_install:
  - echo "before_install"

script:
  - go test -v -race ./...
  - go build

after_success:
  - bash <(curl -s https://codecov.io/bash)